blank_issues_enabled: true
contact_links:
  - name: Neko Discord Server
    url: https://discord.gg/6udzwjH
    about: Please use our Discord for questions or help. Issues should be used for bug reports, feature requests or similar.